spring.application.name=servico-veiculos
spring.datasource.url=jdbc:postgresql://localhost:5432/prova_corporativos
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true